Loading training set...
C:\Users\kytom\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\utils\data\sampler.py:64: UserWarning: `data_source` argument is not used and will be removed in 2.2.0.You may still have custom implementation that utilizes it.
  warnings.warn("`data_source` argument is not used and will be removed in 2.2.0."

Num images:  1
Image shape: [4, 1024, 1024]
Label shape: [0]

Constructing networks...
Setting up augmentation...
Distributing across 1 GPUs...
Setting up training phases...
Exporting sample images...
Traceback (most recent call last):
  File "C:\Users\kytom\Desktop\UST\swin_gan\SwinGAN\stylegan2\train.py", line 566, in <module>
    main() # pylint: disable=no-value-for-parameter
    ^^^^^^
  File "C:\Users\kytom\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kytom\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\kytom\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kytom\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kytom\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kytom\Desktop\UST\swin_gan\SwinGAN\stylegan2\train.py", line 559, in main
    subprocess_fn(rank=0, args=args, temp_dir=temp_dir, swin=swin)
  File "C:\Users\kytom\Desktop\UST\swin_gan\SwinGAN\stylegan2\train.py", line 386, in subprocess_fn
    training_loop.training_loop(rank=rank, **args, swin=swin)
  File "C:\Users\kytom\Desktop\UST\swin_gan\SwinGAN\stylegan2\training\training_loop.py", line 296, in training_loop
    save_image_grid(
  File "C:\Users\kytom\Desktop\UST\swin_gan\SwinGAN\stylegan2\training\training_loop.py", line 85, in save_image_grid
    assert C in [1, 3]
           ^^^^^^^^^^^
AssertionError
